export const copy = {
  en: {
    meta: {
      title: "Iberian Caucasus — Apartment management in Tbilisi",
      description:
        "Iberian Caucasus manages short and mid-stay apartments in Tbilisi on Airbnb and Booking.com. Management from 20%. Request a free analysis of your apartment.",
    },
    city: "Tbilisi",
    currency: "GEL",
    languageLabel: "Language",
    skip: "Skip to the analysis",
    onThisPage: "On this page",
    menu: "Menu",
    close: "Close",
    navCta: "Free analysis",
    navLogin: "Log in",
    skipLogin: "Skip to log in",
    nav: [
      ["#service", "Services"],
      ["#process", "How it works"],
      ["#pricing", "Pricing"],
      ["#reporting", "Reporting"],
      ["#contact", "Contact"],
    ],
    footer: {
      blurb: "Short and mid-stay apartment management in Tbilisi.",
      reply: "Alberto Roldán replies from this address.",
      fee: "Fee",
      feeLine: "Management from 20%.",
      feeNote: "The analysis names the fee for your apartment before you decide.",
    },
    hero: {
      kicker: "Short and mid-stay · Tbilisi",
      title: "We look after your apartment on Airbnb and Booking.",
      illustrative: "Illustrative",
      caption: "A drawing of a balcony in Tbilisi. Not an apartment we manage.",
      lede: "Iberian Caucasus manages short and mid-stay rentals for apartment owners in Tbilisi. We list it, price it, sync the calendars, talk to guests, and coordinate check-in, cleaning and repairs. You keep the apartment.",
      fee: "Management from 20%.",
      cta: "Request a free analysis",
    },
    benefits: {
      kicker: "For the owner",
      title: "What the management is for.",
      items: [
        ["Less work", "One point of contact for guest communication, check-ins, cleaning and maintenance coordination."],
        ["Clear finances", "Monthly reporting of bookings, income, expenses and occupancy."],
        ["Informed decisions", "An apartment-specific assessment before committing to short- or mid-term rentals."],
      ],
    },
    service: {
      kicker: "Services",
      title: "What we do with the apartment.",
      groups: [
        {
          title: "Listing and pricing",
          items: [
            ["Listing", "We publish the apartment on Airbnb and Booking.com and keep the text and photos honest."],
            ["Pricing and calendar", "We set the nightly price and which dates stay open."],
          ],
        },
        {
          title: "Reservations and guest communication",
          items: [
            ["Calendar sync", "A night taken on one platform is closed on the other."],
            ["Guests", "We answer guests, from the first question to the day they leave."],
          ],
        },
        {
          title: "Cleaning, check-ins and maintenance",
          items: [
            ["Check-in and check-out", "We coordinate arrival and departure."],
            ["Cleaning and linen", "We coordinate the turnover: cleaning and bed linen."],
            ["Maintenance", "We handle issues and tell you what happened."],
          ],
        },
        {
          title: "Financial reporting",
          items: [
            ["Monthly report", "Bookings, income, expenses, occupancy and issues, once a month."],
          ],
        },
      ],
    },
    process: {
      kicker: "How it works",
      title: "What happens before we manage anything.",
      steps: [
        ["Send the apartment", "Address, size, and what it earns today, if it earns anything."],
        ["We look, then we talk", "If short or mid-stay is a poor fit, we say so. The analysis does not oblige you."],
        ["Then we run it", "Listing, guests, turnovers. After the first month, you get a report."],
      ],
    },
    pricing: {
      kicker: "Pricing",
      title: "Management starts at 20%.",
      from: "From",
      one: "The exact fee is confirmed after we review the apartment. It is named in the analysis, before you decide.",
      two: "This page does not define what the percentage is calculated on. It also does not treat cleaning, linen, platform commissions or repairs as part of the fee. Those points are settled in the review.",
    },
    reporting: {
      kicker: "Reporting",
      title: "What you receive each month.",
      lede: "After a month with your apartment, you receive a report: reservations, gross booking revenue, occupancy, operating expenses and the payout to you. Issues that need a decision are in the same note. It is sent by email.",
      login: "Owner login",
      sampleAria: "Illustrative monthly report with sample data",
      sampleFlag: "Illustrative report — sample data",
      sampleTitle: "Sample month",
      sampleNote: "Not a client. These figures are layout only. They do not show how the fee is calculated.",
      rows: [
        ["Reservations", "4", false],
        ["Gross booking revenue", "3,150 GEL", false],
        ["Occupancy", "48%", false],
        ["Operating expenses", "410 GEL", false],
        ["Owner payout", "2,180 GEL", true],
      ],
    },
    contact: {
      portrait: "Photograph to be added. This is not a portrait.",
      kicker: "Contact",
      name: "Alberto Roldán",
      lede: "Alberto Roldán is the person behind Iberian Caucasus. Owners write to him. He is the person who replies.",
      trustLead: "There are no client counts, reviews or case studies on this page. An owner can check the following.",
      trust: [
        "Services set out in plain language",
        "A fee that starts at 20%, confirmed after a review of the apartment",
        "An analysis of your apartment before you commit",
        "Monthly reporting of the bookings and the money",
        "Direct contact with Alberto Roldán",
      ],
    },
    analysis: {
      kicker: "Free analysis",
      title: "Tell us about this apartment.",
      lede: "We will not answer with a city average. The reply is an estimate for this address, after we have looked at it, and it is free. Management starts from 20%.",
      hint: "Name, a way to reply, the location and the number of bedrooms are required. The rest can wait.",
      name: "Name",
      email: "Email",
      phone: "Phone",
      address: "Apartment location",
      bedrooms: "Number of bedrooms",
      choose: "Choose",
      optional: "Optional",
      size: "Size, m²",
      furnished: "Furnishing",
      condition: "Condition",
      rent: "Current rental income, GEL / month",
      notRented: "Not currently rented",
      notes: "Additional notes",
      company: "Company",
      sending: "Sending…",
      sent: "Request sent",
      submit: "Request the free analysis",
      errorLead: "The request did not go through. Write to us at",
      errorTail: "with the same details.",
    },
    login: {
      kicker: "Owner area",
      title: "Log in.",
      lede: "For apartment owners.",
      email: "Email",
      password: "Password",
      submit: "Log in",
      emailError: "Add the email on the account.",
      passwordError: "Add the password.",
    },
    signup: {
      kicker: "Sign up",
      title: "Send us an email.",
      lede: "To sign up, write to us. We open owner accounts by email.",
      subject: "Owner sign up",
    },
    errors: {
      name: "Add your name.",
      email: "Add an email we can reply to.",
      phone: "Add a phone number we can use.",
      contact: "Add an email or a phone number.",
      address: "Add the apartment's location in Tbilisi.",
      bedrooms: "Choose the number of bedrooms.",
      sqm: "Add the size in square metres, or leave it blank.",
      rent: "Add the current monthly rent, or leave it blank.",
    },
    beds: [
      ["Studio", "Studio"],
      ["1", "1"],
      ["2", "2"],
      ["3", "3"],
      ["4+", "4+"],
    ],
    furnished: [
      ["Furnished", "Furnished"],
      ["Partly furnished", "Partly furnished"],
      ["Unfurnished", "Unfurnished"],
    ],
    condition: [
      ["Ready to host", "Ready to host"],
      ["Needs some work", "Needs some work"],
      ["I'm not sure", "I'm not sure"],
    ],
    summary: {
      forAnalysis: "For the analysis",
      noRent: "No rent entered",
      vacantNote: "No monthly rent to set beside a hosting estimate.",
      rentNote: "Current rent, as you entered it. Not a hosting forecast.",
      locationMissing: "Location not added",
      sizeMissing: "Size not added",
      detailsMissing: "Furnishing and condition not added",
      sentBefore: "This is a request for an estimate, not the estimate. We have the details and will reply to",
      sentAfter: "after we have looked at the apartment.",
      idle: "An income figure here would be a guess. Send the apartment and we will come back with an analysis: whether short or mid-stay is worth it, and the fee, which starts from 20%.",
    },
    mail: {
      subject: (address) => `Free apartment analysis — ${address}`,
      intro: "Free apartment analysis",
      name: "Name",
      email: "Email",
      phone: "Phone",
      address: "Apartment location",
      bedrooms: "Bedrooms",
      size: "Size",
      furnished: "Furnishing",
      condition: "Condition",
      rent: "Current rental income",
      notes: "Notes",
      notRented: "Not currently rented",
      perMonth: "GEL per month",
      empty: "—",
      closing: "This is a request for an analysis, not a booking.",
      language: "English",
    },
  },
  ka: {
    meta: {
      title: "Iberian Caucasus — ბინების მართვა თბილისში",
      description:
        "Iberian Caucasus თბილისში მოკლე და საშუალოვადიან ბინებს მართავს Airbnb-სა და Booking.com-ზე. მართვა 20%-იდან. მოითხოვეთ ბინის უფასო ანალიზი.",
    },
    city: "თბილისი",
    currency: "ლარი",
    languageLabel: "ენა",
    skip: "ანალიზზე გადასვლა",
    onThisPage: "ამ გვერდზე",
    menu: "მენიუ",
    close: "დახურვა",
    navCta: "უფასო ანალიზი",
    navLogin: "შესვლა",
    skipLogin: "შესვლაზე გადასვლა",
    nav: [
      ["#service", "სერვისები"],
      ["#process", "როგორ მუშაობს"],
      ["#pricing", "ფასი"],
      ["#reporting", "ანგარიშები"],
      ["#contact", "კონტაქტი"],
    ],
    footer: {
      blurb: "მოკლე და საშუალოვადიანი ბინების მართვა თბილისში.",
      reply: "ამ მისამართიდან პასუხობს ალბერტო როლდანი.",
      fee: "საკომისიო",
      feeLine: "მართვა 20%-იდან.",
      feeNote: "ანალიზში თქვენი ბინის საკომისიო წერია, სანამ გადაწყვეტთ.",
    },
    hero: {
      kicker: "მოკლე და საშუალოვადიანი · თბილისი",
      title: "თქვენს ბინას Airbnb-სა და Booking-ზე ვუვლით.",
      illustrative: "საილუსტრაციო",
      caption: "თბილისის აივნის ნახატი. ეს არ არის ბინა, რომელსაც ვმართავთ.",
      lede: "Iberian Caucasus თბილისში ბინის მფლობელებისთვის მოკლე და საშუალოვადიან გაქირავებას მართავს. ბინას ვაქვეყნებთ, ფასს ვადგენთ, კალენდრებს ვაერთიანებთ, სტუმრებს ვპასუხობთ და ვაკოორდინებთ შესვლას, დალაგებასა და შეკეთებას. ბინა თქვენ გრჩებათ.",
      fee: "მართვა 20%-იდან.",
      cta: "მოითხოვეთ უფასო ანალიზი",
    },
    benefits: {
      kicker: "მფლობელისთვის",
      title: "რისთვისაა ეს მართვა.",
      items: [
        ["ნაკლები საქმე", "ერთი საკონტაქტო პირი სტუმრებთან საუბრისთვის, შესვლა-გასვლისთვის, დალაგებისა და მოვლის კოორდინაციისთვის."],
        ["ცხადი ფინანსები", "ყოველთვიური ანგარიში ჯავშნებზე, შემოსავალზე, ხარჯებსა და დატვირთვაზე."],
        ["გაცნობიერებული გადაწყვეტილება", "კონკრეტული ბინის შეფასება, სანამ მოკლე ან საშუალოვადიან გაქირავებას დათანხმდებით."],
      ],
    },
    service: {
      kicker: "სერვისები",
      title: "რას ვაკეთებთ ბინასთან.",
      groups: [
        {
          title: "განცხადება და ფასი",
          items: [
            ["განცხადება", "ბინას ვაქვეყნებთ Airbnb-სა და Booking.com-ზე. აღწერა და ფოტოები ბინას შეესაბამება."],
            ["ფასი და კალენდარი", "ვადგენთ ღამის ფასს და რომელ დღეებშია თავისუფალი."],
          ],
        },
        {
          title: "ჯავშნები და სტუმრებთან საუბარი",
          items: [
            ["კალენდრის სინქრონიზაცია", "ერთ პლატფორმაზე დაჯავშნილი ღამე მეორეზე იკეტება."],
            ["სტუმრები", "სტუმრებს ვპასუხობთ პირველი კითხვიდან გასვლის დღემდე."],
          ],
        },
        {
          title: "დალაგება, შესვლა და მოვლა",
          items: [
            ["შესვლა და გასვლა", "ჩამოსვლასა და გასვლას ვაკოორდინებთ."],
            ["დალაგება და თეთრეული", "ბინის მომზადებას ვაკოორდინებთ: დალაგებასა და თეთრეულს."],
            ["მოვლა", "პრობლემას ვაგვარებთ და გეუბნებით, რა მოხდა."],
          ],
        },
        {
          title: "ფინანსური ანგარიში",
          items: [
            ["ყოველთვიური ანგარიში", "თვეში ერთხელ: ჯავშნები, შემოსავალი, ხარჯები, დატვირთვა და პრობლემები."],
          ],
        },
      ],
    },
    process: {
      kicker: "როგორ მუშაობს",
      title: "რა ხდება, სანამ რამის მართვას დავიწყებთ.",
      steps: [
        ["გამოგვიგზავნეთ ბინა", "მისამართი, ფართი და რას იღებს დღეს, თუ რამეს იღებს."],
        ["ჯერ ვნახულობთ, მერე ვსაუბრობთ", "თუ მოკლე ან საშუალოვადიანი არ უხდება, ამას გეტყვით. ანალიზი არაფერზე გავალდებულებთ."],
        ["შემდეგ უკვე ვმართავთ", "განცხადება, სტუმრები, ბინის მომზადება. პირველი თვის შემდეგ ანგარიშს იღებთ."],
      ],
    },
    pricing: {
      kicker: "ფასი",
      title: "მართვა 20%-იდან იწყება.",
      from: "მინიმუმ",
      one: "ზუსტი საკომისიო ბინის ნახვის შემდეგ დგინდება. ანალიზში წერია, სანამ გადაწყვეტილებას მიიღებთ.",
      two: "ამ გვერდზე არ წერია, რაზე ითვლება პროცენტი. დალაგება, თეთრეული, პლატფორმის საკომისიო და შეკეთება საკომისიოში არ შედის. ეს განხილვისას წყდება.",
    },
    reporting: {
      kicker: "ანგარიშები",
      title: "რას იღებთ ყოველ თვეში.",
      lede: "ბინასთან ერთი თვის შემდეგ იღებთ ანგარიშს: ჯავშნები, ჯავშნიდან მიღებული თანხა, დატვირთვა, საოპერაციო ხარჯები და თქვენთვის გადასარიცხი თანხა. რასაც გადაწყვეტილება სჭირდება, იმავე წერილშია. იგზავნება ელფოსტით.",
      login: "მფლობელის შესვლა",
      sampleAria: "საილუსტრაციო ყოველთვიური ანგარიში ნიმუშის ციფრებით",
      sampleFlag: "ნიმუშის მონაცემები",
      sampleTitle: "ნიმუშის თვე",
      sampleNote: "ეს კლიენტი არ არის. ციფრები მხოლოდ განლაგებისთვისაა და არ აჩვენებს, როგორ ითვლება საკომისიო.",
      rows: [
        ["ჯავშნები", "4", false],
        ["ჯავშნების მთლიანი შემოსავალი", "3 150 ლარი", false],
        ["დატვირთვა", "48%", false],
        ["საოპერაციო ხარჯები", "410 ლარი", false],
        ["მფლობელის თანხა", "2 180 ლარი", true],
      ],
    },
    contact: {
      portrait: "ფოტო დაემატება. ეს პორტრეტი არ არის.",
      kicker: "კონტაქტი",
      name: "ალბერტო როლდანი",
      lede: "ალბერტო როლდანი დგას Iberian Caucasus-ის უკან. მფლობელები მას სწერენ. პასუხსაც ის სწერს.",
      trustLead: "ამ გვერდზე არ არის კლიენტების რიცხვი, შეფასებები ან მაგალითები. მფლობელს შეუძლია ეს შეამოწმოს.",
      trust: [
        "სერვისები მარტივ ენაზეა გაწერილი",
        "საკომისიო 20%-იდან იწყება და ბინის ნახვის შემდეგ დგინდება",
        "ბინის ანალიზი, სანამ დათანხმდებით",
        "ყოველთვიური ანგარიში ჯავშნებსა და ფულზე",
        "პირდაპირი კონტაქტი ალბერტო როლდანთან",
      ],
    },
    analysis: {
      kicker: "უფასო ანალიზი",
      title: "მოგვიყევით ამ ბინის შესახებ.",
      lede: "ქალაქის საშუალოს არ გეტყვით. პასუხი ამ მისამართის შეფასებაა, მას შემდეგ რაც ვნახავთ, და უფასოა. მართვა 20%-იდან იწყება.",
      hint: "სახელი, საკონტაქტო საშუალება, მდებარეობა და საძინებლების რაოდენობა სავალდებულოა. დანარჩენი შეიძლება მოგვიანებით.",
      name: "სახელი",
      email: "ელფოსტა",
      phone: "ტელეფონი",
      address: "ბინის მდებარეობა",
      bedrooms: "საძინებლების რაოდენობა",
      choose: "აირჩიეთ",
      optional: "არასავალდებულო",
      size: "ფართი, მ²",
      furnished: "ავეჯი",
      condition: "მდგომარეობა",
      rent: "ახლანდელი შემოსავალი ქირიდან, ლარი / თვეში",
      notRented: "ამჟამად არ ქირავდება",
      notes: "დამატებითი შენიშვნა",
      company: "კომპანია",
      sending: "იგზავნება…",
      sent: "მოთხოვნა გაგზავნილია",
      submit: "მოითხოვეთ უფასო ანალიზი",
      errorLead: "მოთხოვნა არ გაიგზავნა. იგივე დეტალებით მოგვწერეთ",
      errorTail: "",
    },
    login: {
      kicker: "მფლობელის ზონა",
      title: "შესვლა.",
      lede: "ბინის მფლობელებისთვის.",
      email: "ელფოსტა",
      password: "პაროლი",
      submit: "შესვლა",
      emailError: "მიუთითეთ ანგარიშის ელფოსტა.",
      passwordError: "მიუთითეთ პაროლი.",
    },
    signup: {
      kicker: "რეგისტრაცია",
      title: "მოგვწერეთ.",
      lede: "რეგისტრაციისთვის მოგვწერეთ. მფლობელის ანგარიშს ელფოსტით ვხსნით.",
      subject: "მფლობელის რეგისტრაცია",
    },
    errors: {
      name: "მიუთითეთ სახელი.",
      email: "მიუთითეთ ელფოსტა, რომელზეც გიპასუხებთ.",
      phone: "მიუთითეთ ტელეფონი, რომელზეც დაგიკავშირდებით.",
      contact: "მიუთითეთ ელფოსტა ან ტელეფონი.",
      address: "მიუთითეთ ბინის მდებარეობა თბილისში.",
      bedrooms: "აირჩიეთ საძინებლების რაოდენობა.",
      sqm: "მიუთითეთ ფართი კვადრატულ მეტრებში, ან დატოვეთ ცარიელი.",
      rent: "მიუთითეთ ახლანდელი თვიური ქირა, ან დატოვეთ ცარიელი.",
    },
    beds: [
      ["Studio", "სტუდიო"],
      ["1", "1"],
      ["2", "2"],
      ["3", "3"],
      ["4+", "4+"],
    ],
    furnished: [
      ["Furnished", "მოწყობილია"],
      ["Partly furnished", "ნაწილობრივაა მოწყობილი"],
      ["Unfurnished", "მოწყობილი არ არის"],
    ],
    condition: [
      ["Ready to host", "სტუმრისთვის მზადაა"],
      ["Needs some work", "ცოტა სამუშაო სჭირდება"],
      ["I'm not sure", "ზუსტად არ ვიცი"],
    ],
    summary: {
      forAnalysis: "ანალიზისთვის",
      noRent: "ქირა მითითებული არ არის",
      vacantNote: "თვიური ქირა არ გვაქვს, რომ მასპინძლობის შეფასებას გვერდით დავდოთ.",
      rentNote: "ახლანდელი ქირა, როგორც თქვენ მიუთითეთ. ეს მასპინძლობის პროგნოზი არ არის.",
      locationMissing: "მდებარეობა მითითებული არ არის",
      sizeMissing: "ფართი მითითებული არ არის",
      detailsMissing: "ავეჯი და მდგომარეობა მითითებული არ არის",
      sentBefore: "ეს შეფასების მოთხოვნაა, არა თავად შეფასება. დეტალები მივიღეთ და ბინის ნახვის შემდეგ გიპასუხებთ:",
      sentAfter: "",
      idle: "შემოსავლის ციფრი აქ ვარაუდი იქნებოდა. გამოგვიგზავნეთ ბინა და ანალიზით დაგიბრუნდებით: ღირს თუ არა მოკლე ან საშუალოვადიანი და რა იქნება საკომისიო. ის 20%-იდან იწყება.",
    },
    mail: {
      subject: (address) => `ბინის უფასო ანალიზი — ${address}`,
      intro: "ბინის უფასო ანალიზი",
      name: "სახელი",
      email: "ელფოსტა",
      phone: "ტელეფონი",
      address: "ბინის მდებარეობა",
      bedrooms: "საძინებლები",
      size: "ფართი",
      furnished: "ავეჯი",
      condition: "მდგომარეობა",
      rent: "ახლანდელი შემოსავალი ქირიდან",
      notes: "შენიშვნა",
      notRented: "ამჟამად არ ქირავდება",
      perMonth: "ლარი თვეში",
      empty: "—",
      closing: "ეს ანალიზის მოთხოვნაა, არა ჯავშანი.",
      language: "Georgian",
    },
  },
};
